name: Deploy to GitHub Pages

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  test-deploy:
    if: github.event_name != 'push'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci

      - name: Clone FGDDumper
        run: git clone https://github.com/Source2Wiki/FGDDumper
      - name: Run FGDDumper
        run: dotnet run --project FGDDumper/EntityPageTools -- --root . --generate_mdx --no_listen

      - name: Test build website
        run: npm run build
  deploy:
    if: github.event_name != 'pull_request'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      
      - name: Clone FGDDumper
        run: git clone https://github.com/Source2Wiki/FGDDumper
      - name: Run FGDDumper
        run: dotnet run --project FGDDumper/EntityPageTools -- --root ./ --generate_mdx --no_listen

      - name: Deploy to GitHub Pages
        env:
          USE_SSH: true
        run: |
          git config --global user.email "angelcazacu8@gmail.com"
          git config --global user.name "angel_foxxo"
          npm ci
          npm run deploy